name: Bug 报告
description: 反馈运行问题（请附诊断信息）
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        请先在扩展设置页 -> 诊断与调试中「复制诊断」或「下载诊断 JSON」。
        诊断不包含原文消息与 API Key，但仍可能含有敏感摘要，请自行确认后再提交。
  - type: input
    id: version
    attributes:
      label: 扩展版本
      placeholder: "例如：0.1.0"
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: 影响平台
      options:
        - Telegram Web
        - WhatsApp Web
        - Slack Web
        - 其他
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: 浏览器与版本
      placeholder: "例如：Chrome 121.0 / Edge 121.0"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 复现步骤
      placeholder: "1. ... 2. ... 3. ..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 预期结果
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: 实际结果
    validations:
      required: true
  - type: textarea
    id: diagnostics
    attributes:
      label: 诊断信息（粘贴 JSON）
      render: json
    validations:
      required: false
  - type: checkboxes
    id: privacy
    attributes:
      label: 隐私确认
      options:
        - label: 我已检查并确认诊断内容不包含敏感原文或 API Key
          required: true
